import random
import time

class Student:
    def __init__(self, id, name, age, grade):
        self.id = id
        self.name = name
        self.age = age
        self.grade = grade
        self.scores = []
        self.badges = []

    def take_quiz(self, subject):
        score = random.randint(60, 100)
        self.scores.append({"subject": subject, "score": score})
        print(f"{self.name} took a {subject} quiz and scored {score}! 🎯")
        if score >= 90:
            self.earn_badge(f"{subject} Star")

    def earn_badge(self, badge):
        if badge not in self.badges:
            self.badges.append(badge)
            print(f"{self.name} earned a badge: {badge} 🏅")

    def average_score(self):
        if not self.scores:
            return 0
        total = sum(s["score"] for s in self.scores)
        return total / len(self.scores)

    def report(self):
        print(f"--- Report for {self.name} ---")
        print(f"Age: {self.age}, Grade: {self.grade}")
        if self.scores:
            for s in self.scores:
                print(f"{s['subject']}: {s['score']}")
            print(f"Average Score: {self.average_score():.2f}")
        else:
            print("No quizzes taken yet.")
        if self.badges:
            print("Badges:", ", ".join(self.badges))
        print("----------------------------\n")

def generate_students(num=10):
    names = ["Alex", "Ben", "Cara", "Dina", "Eli", "Fay", "Gabe", "Hana", "Ivy", "Jack"]
    grades = ["1st", "2nd", "3rd", "4th", "5th", "6th"]
    students = []
    for i in range(1, num+1):
        student = Student(
            id=i,
            name=random.choice(names),
            age=random.randint(6, 12),
            grade=random.choice(grades)
        )
        students.append(student)
    return students

def run_quizzes(students, subjects):
    for student in students:
        for subject in subjects:
            student.take_quiz(subject)
            time.sleep(0.02)

def show_reports(students):
    for student in students:
        student.report()
        time.sleep(0.02)

def random_activity(student):
    activities = ["Reading", "Drawing", "Coding", "Sports", "Music"]
    activity = random.choice(activities)
    print(f"{student.name} is doing {activity} today! 🎨🏀🎵💻📚")

def daily_routine(students):
    print("\n--- Daily Routine ---")
    for student in students:
        random_activity(student)
        time.sleep(0.02)
    print("--------------------\n")

def weekly_summary(students):
    print("\n--- Weekly Summary ---")
    for student in students:
        print(f"{student.name} participated in {len(student.scores)} quizzes and earned {len(student.badges)} badges!")
    print("----------------------\n")

def leaderboard(students):
    print("\n--- Leaderboard 🏆 ---")
    sorted_students = sorted(students, key=lambda s: s.average_score(), reverse=True)
    for i, student in enumerate(sorted_students, 1):
        print(f"{i}. {student.name} - Avg Score: {student.average_score():.2f}")
    print("----------------------\n")

def random_event(students):
    events = [
        "found a hidden treasure! 💰",
        "helped a friend and gained friendship points! 🤝",
        "solved a tricky puzzle! 🧩",
        "got caught in a silly prank! 🤪",
        "learned a new skill! ✨"
    ]
    student = random.choice(students)
    event = random.choice(events)
    print(f"Random Event: {student.name} {event}")

def main():
    print("Welcome to Study Buds Simulator! 🎉\n")
    students = generate_students(10)
    subjects = ["Math", "Science", "English", "History"]

    print("Running quizzes for all students...\n")
    run_quizzes(students, subjects)

    daily_routine(students)

    print("\nGenerating reports...\n")
    show_reports(students)

    weekly_summary(students)

    leaderboard(students)

    print("\nTriggering random events...\n")
    for _ in range(5):
        random_event(students)
        time.sleep(0.5)

    print("\nAll done! Study Buds rocks! 🚀")

if __name__ == "__main__":
    main()
    print("Generated by Study Buds AI (AI may make mistakes, please review code before use.)")

import random
import time

class Student:
    def __init__(self, id, name, age, grade):
        self.id = id
        self.name = name
        self.age = age
        self.grade = grade
        self.scores = []
        self.badges = []
    def take_quiz(self, subject):
        score = random.randint(60, 100)
        self.scores.append({"subject": subject, "score": score})
        print(f"{self.name} took a {subject} quiz and scored {score}! 🎯")
        if score >= 90:
            self.earn_badge(f"{subject} Star")
    def earn_badge(self, badge):
        if badge not in self.badges:
            self.badges.append(badge)
            print(f"{self.name} earned a badge: {badge} 🏅")
    def average_score(self):
        if not self.scores:
            return 0
        total = sum(s["score"] for s in self.scores)
        return total / len(self.scores)
    def report(self):
        print(f"--- Report for {self.name} ---")
        print(f"Age: {self.age}, Grade: {self.grade}")
        if self.scores:
            for s in self.scores:
                print(f"{s['subject']}: {s['score']}")
            print(f"Average Score: {self.average_score():.2f}")
        else:
            print("No quizzes taken yet.")
        if self.badges:
            print("Badges:", ", ".join(self.badges))
        print("----------------------------\n")